namespace NormandiaNetworking.ro.mpp
{
    public enum RequestType
    {
        LOGIN, LOGOUT, SIGNUP, GET_COMPETITIONS, REGISTER_PARTICIPANT, GET_PARTICIPANTS_BY_COMPETITION, GET_ALL_CLIENTS,GET_ALL_CURSE,GET_ALL_REZERVARI,REGISTER_REZERVARE,REGISTER_SEAT,GET_ALL_SEATS
    }
}